# Generated by Django 5.1.6 on 2025-03-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
