# Generated by Django 5.1.6 on 2025-03-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
