# Generated by Django 5.1.6 on 2025-03-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_comment_rating_delete_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
